name: profilecli
description: Download PGO profile

inputs:
  endpoint:
    description: Pyroscope API endpoint to fetch profiling data.
    required: true
  query:
    description: Pyroscope query used to filter profiling data.
    required: true
  username:
    description: Username for authentication with the profile endpoint.
    required: true
  password:
    description: Password for authentication with the profile endpoint.
    required: true
  output_path:
    description: Path to the output file where the profile will be saved
    required: false
    default: default.pgo
  range_from:
    description: Start time for the profiling range (e.g., 'now-24h').
    required: false
    default: now-24h
  range_to:
    description: End time for the profiling range (e.g., 'now').
    required: false
    default: now
  profile_type:
    description: Type of profile to fetch.
    required: false
    default: process_cpu:samples:count:cpu:nanoseconds
  profilecli_version:
    description: "Version of profilecli to use."
    required: false
    default: "1.1.5"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Generate and share timestamp
      shell: sh
      run: echo PROFILECLI_ACTION_TMP_FILE=/tmp/profilecli-action-$(date +%s%3N).pgo >> $GITHUB_ENV

    - name: Download profilecli executable
      shell: sh
      env:
        PROFILECLI_VERSION: ${{ inputs.profilecli_version }}
      run: |
        curl -fL "https://github.com/grafana/pyroscope/releases/download/v${PROFILECLI_VERSION}/profilecli_${PROFILECLI_VERSION}_linux_amd64.tar.gz" | tar xvz
        chmod +x profilecli

    - name: Download profiling
      shell: sh
      env:
        PROFILECLI_ENDPOINT: ${{ inputs.endpoint }}
        PROFILECLI_QUERY: ${{ inputs.query }}
        PROFILECLI_USERNAME: ${{ inputs.username }}
        PROFILECLI_PASSWORD: ${{ inputs.password }}
        PROFILECLI_RANGE_FROM: ${{ inputs.range_from }}
        PROFILECLI_RANGE_TO: ${{ inputs.range_to }}
        PROFILECLI_PROFILE_TYPE: ${{ inputs.profile_type }}
        PROFILECLI_OUTPUT_PATH: ${{ inputs.output_path }}
      run: |
        ./profilecli query merge \
          --from="$PROFILECLI_RANGE_FROM" \
          --to="$PROFILECLI_RANGE_TO" \
          --profile-type="$PROFILECLI_PROFILE_TYPE" \
          --query="$PROFILECLI_QUERY" \
          --output="pprof=$PROFILECLI_ACTION_TMP_FILE" \
          --url="$PROFILECLI_ENDPOINT" \
          --username="$PROFILECLI_USERNAME" \
          --password="$PROFILECLI_PASSWORD"

    - name: Replace previous profile with the new one
      shell: sh
      env:
        PROFILECLI_OUTPUT_PATH: ${{ inputs.output_path }}
      run: mv -f $PROFILECLI_ACTION_TMP_FILE "$PROFILECLI_OUTPUT_PATH"

    - name: Commit, push, and create pull request
      shell: sh
      env:
        PROFILECLI_OUTPUT_PATH: ${{ inputs.output_path }}
        PROFILECLI_GH_REPOSITORY: ${{ github.repository }}
      run: |
        if git status -s "$PROFILECLI_OUTPUT_PATH" | grep -qE '(M|\?\?)'; then
          git config --global user.email "botify-labs-profilecli-action@users.noreply.github.com"
          git config --global user.name "profilecli-action"
          PROFILECLI_ACTION_BRANCH=profilecli-action/generate-profile-$(date +%s%3N)
          git switch -c "$PROFILECLI_ACTION_BRANCH"
          git add "$PROFILECLI_OUTPUT_PATH"
          git commit -m "Generate profile"
          git push -u origin "$PROFILECLI_ACTION_BRANCH"
          gh pr create \
            --title "Generate Go profile" \
            --body "Autogenerated." \
            --repo "$PROFILECLI_GH_REPOSITORY" \
            --head "$PROFILECLI_ACTION_BRANCH"
        else
          echo "No changes detected."
        fi
